services:

  db:
    image: mariadb:10.5
    container_name: mariadb-db
    restart: always
    environment:
      MYSQL_DATABASE: financesDB
      MYSQL_USER: MyP
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mydata

  django:
    build:
      context: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"

#un volumen guarda info del programa, aunque se elimine, actualice el contenedor (para la db) :)
volumes:
  db_data:
